baseURL = 'https://Sauravroy34.github.io'
languageCode = 'en-us'
title = 'Saurav Kumar Roy'
theme = 'hugo-theme-tokiwa'
enableRobotsTXT = true


[params]
math = false # opt individual pages into KaTeX with `math = true` front matter
env = "production" # for Google Analytics and DISQUS.
bannerFont = "fonts/exampleFont" # custom your own font for the title.
postDateFormat = "2006-1-2" # override custom date format posts.
favicon = "/favicon.svg"
metaDescription = "Saurav Kumar Roy's work in AI for science, deep learning, machine learning, chemistry, and scientific computing."

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Research"
    weight = 2
    identifier = "research"
    url = "/research/"
  [[menu.main]]
    name = "Posts"
    weight = 3
    identifier = "posts"
    url = "/posts/"
  [[menu.main]]
    name = "CV"
    url = "https://drive.google.com/file/d/1BV_OGGco2SOGoaLPfLAuG_YuVw4v-ou0/view?usp=sharing"
    identifier = "CV"
    weight = 4

[params.social]
github="https://github.com/Sauravroy34"
linkedin = "https://www.linkedin.com/in/saurav-kumar-roy-0aa286280"
twitter="https://x.com/Sauravnotfound"
